### PR TITLE
utils: use function_exists() guard on head() and last() to play nice with illuminate/database

### PR DESCRIPTION
**Pull request by martinlindhe**
utils: use function_exists() guard on head() and last() to play nice together with https://github.com/illuminate/support/blob/master/helpers.php, used by illuminate/database (laravel eloquent)

### CODE REVIEW

**Comment by martinlindhe** [comment]
This was needed to solve
Fatal error: Cannot redeclare head() (previously declared in /var/www/proj/vendor/illuminate/support/helpers.php:482) in /var/www/proj/vendor/phacility/libphutil/src/utils/utils.php on line 679

**Comment by chadlittle** [comment]
We are not able to take pull requests (GitHub is just a mirror). Please read up on Contributing changes in our documentation here: https://secure.phabricator.com/book/phabcontrib/article/contributing_code/

**Comment by martinlindhe** [comment]
right. it slipped my mind.. will follow the proper procedure.

**Comment by martinlindhe** [comment]
reported as https://secure.phabricator.com/T7476

**Pull request closed without merging**
